(() => {
 const content=window.portfolioContent||{projects:[],articles:[],contacts:[]};
 const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const safe=v=>{try{const u=new URL(v,location.href);return ["http:","https:","mailto:","tel:"].includes(u.protocol)?u.href:""}catch{return ""}};
 const link=(url,label,cls="")=>{const href=safe(url);return href?`<a class="${cls}" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${label}</a>`:`<span class="${cls} unavailable">${label}</span>`};
 const projects=content.projects||[];document.querySelector("#project-count").textContent=`(${String(projects.length).padStart(2,"0")})`;document.querySelector("#project-empty").hidden=projects.length>0;
 document.querySelector("#project-grid").innerHTML=projects.map((p,i)=>`<article class="project-card"><div class="project-visual visual-${i%3}"><span class="visual-index">PROJECT / ${String(i+1).padStart(2,"0")}</span><div class="visual-orbit"></div><div class="visual-icon">${["⌘","◈","↗"][i%3]}</div><span class="visual-lines"></span></div><div class="project-meta"><span>${esc(p.category||"ENGINEERING")}</span><span>${String(i+1).padStart(2,"0")}</span></div><h3>${esc(p.title||"Untitled project")}</h3><p>${esc(p.summary||"")}</p><div class="project-bottom"><div class="tag-list">${(p.stack||[]).map(x=>`<span>${esc(x)}</span>`).join("")}</div>${p.url?link(p.url,"View project ↗","project-link"):""}</div></article>`).join("");
 const articles=content.articles||[];document.querySelector("#article-count").textContent=`(${String(articles.length).padStart(2,"0")})`;document.querySelector("#article-empty").hidden=articles.length>0;
 document.querySelector("#article-list").innerHTML=articles.map((a,i)=>`<article class="article-row"><span class="article-number">${String(i+1).padStart(2,"0")}</span><div class="article-info"><span class="article-date">${esc(a.date||"")}${a.category?` · ${esc(a.category)}`:""}</span><h3>${esc(a.title||"Untitled article")}</h3><p>${esc(a.summary||"")}</p></div>${a.url?link(a.url,"↗","article-arrow"):""}</article>`).join("");
 document.querySelector("#contact-links").innerHTML=(content.contacts||[]).map(c=>`<div class="contact-link"><span class="contact-label">${esc(c.label||"Contact")}</span>${c.url?link(c.url,`${esc(c.text||c.url)} <span>↗</span>`):`<span class="contact-placeholder">${esc(c.text||"Add link in content.js")}</span>`}</div>`).join("");document.querySelector("#year").textContent=new Date().getFullYear();
})();
